

spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.180.242:4406/security_project?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: MlP098)(*

project:
  security:
    browser:
      loginPage: /demo-signIn.html
      loginType: REDIRECT
    code:
      image:
        length: 6
        url: /user/*
    social:
      qq:
          app-id: 101386962
          app-secret: 2a0f820407df400b84a854d054be8b6a
          provider-id: qq