

spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.180.242:4406/security_project?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: MlP098)(*

project:
  security:
    browser:
      loginPage: /demo-signIn.html
      loginType: JSON
    code:
      image:
        length: 6
        url: /user/*